const Table = require("../../models/Table");
const { generateTableQR } = require("../../utils/generateQR");

/**
 * Table Management Service
 * Business logic for admin table CRUD operations with tenant isolation
 *
 * SECURITY RULES:
 * 1. restaurantId ALWAYS from JWT context, NEVER from request body
 * 2. All queries filtered by restaurantId (tenant isolation at DB level)
 * 3. Ownership verified before UPDATE/DELETE (403 if not owner)
 * 4. Soft delete pattern: set isActive: false instead of hard delete
 * 5. QR code generated server-side during table creation (immutable)
 */

class TableService {
  /**
   * Create a new table
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {object} tableData - { tableNumber, capacity, description? }
   * @returns {object} Created table with QR code
   */
  async createTable(restaurantId, tableData) {
    try {
      // Validate required fields
      if (!tableData.tableNumber || !tableData.tableNumber.trim()) {
        const error = new Error("Table number is required");
        error.statusCode = 400;
        throw error;
      }

      // Generate QR code
      // QR points to: {CLIENT_URL}/r/{restaurantId}/t/{tableId}
      // Note: tableId will be generated by MongoDB after create
      // So we'll generate QR after table creation

      const table = await Table.create({
        restaurantId, // From JWT (req.user.restaurantId)
        tableNumber: tableData.tableNumber.trim(),
        capacity: tableData.capacity || 4,
        status: "available",
        isActive: true,
        qrCodeUrl: "", // Temporary, will be filled below
      });

      // CRITICAL: Generate QR code with the actual tableId
      const clientBaseUrl = process.env.CLIENT_URL || "http://localhost:5173";
      const qrCodeUrl = await generateTableQR(
        clientBaseUrl,
        restaurantId,
        table._id.toString(),
      );

      // Update table with QR code
      table.qrCodeUrl = qrCodeUrl;
      await table.save();

      return table.toObject();
    } catch (error) {
      // Handle MongoDB duplicate key error (unique constraint on restaurantId + tableNumber)
      if (error.code === 11000) {
        const err = new Error(
          "Table number already exists for this restaurant",
        );
        err.statusCode = 409;
        throw err;
      }

      // Ensure error has statusCode
      if (!error.statusCode) {
        error.statusCode = 500;
      }
      throw error;
    }
  }

  /**
   * Get all tables for a restaurant
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {object} query - Optional query parameters { status }
   * @returns {array} Tables for the restaurant
   */
  async getTablesByRestaurant(restaurantId, query = {}) {
    try {
      // Build filter with restaurantId (MANDATORY - tenant isolation)
      const filter = { restaurantId, isActive: true }; // Exclude soft-deleted

      // Optional filter by status
      if (query.status) {
        filter.status = query.status;
      }

      // Query with restaurantId filter - returns only this restaurant's tables
      const tables = await Table.find(filter).sort({ tableNumber: 1 }).lean();

      // Ensure every table has a valid QR Data URL
      const clientBaseUrl = process.env.CLIENT_URL || "http://localhost:5173";
      for (const t of tables) {
        if (!t.qrCodeUrl) {
          try {
            t.qrCodeUrl = await generateTableQR(clientBaseUrl, restaurantId, t._id.toString());
            await Table.findByIdAndUpdate(t._id, { qrCodeUrl: t.qrCodeUrl });
          } catch (e) {
            console.warn(`[TableService] Failed to auto-generate QR for table ${t._id}:`, e.message);
          }
        }
      }

      return tables;
    } catch (error) {
      error.statusCode = 500;
      throw error;
    }
  }

  /**
   * Get single table by ID with ownership verification
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {string} tableId - Table ID
   * @returns {object} Table if found and belongs to restaurant
   */
  async getTableById(restaurantId, tableId) {
    try {
      // Find by both ID and restaurantId (ownership verification in query)
      const table = await Table.findOne({
        _id: tableId,
        restaurantId, // CRITICAL: Only return if belongs to this restaurant
      });

      if (!table) {
        const error = new Error("Table not found");
        error.statusCode = 404;
        throw error;
      }

      return table.toObject();
    } catch (error) {
      if (!error.statusCode) {
        error.statusCode = 500;
      }
      throw error;
    }
  }

  /**
   * Update table details
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {string} tableId - Table ID to update
   * @param {object} updateData - Fields to update
   * @returns {object} Updated table
   */
  async updateTable(restaurantId, tableId, updateData) {
    try {
      // Find table first for ownership verification
      const table = await Table.findById(tableId);

      if (!table) {
        const error = new Error("Table not found");
        error.statusCode = 404;
        throw error;
      }

      // CRITICAL SECURITY: Verify table belongs to current restaurant
      if (table.restaurantId.toString() !== restaurantId) {
        const error = new Error(
          "Forbidden: Table does not belong to your restaurant",
        );
        error.statusCode = 403;
        throw error;
      }

      // Check for duplicate table number if updating tableNumber
      if (
        updateData.tableNumber &&
        updateData.tableNumber !== table.tableNumber
      ) {
        const existing = await Table.findOne({
          restaurantId,
          tableNumber: updateData.tableNumber.trim(),
          _id: { $ne: tableId }, // Exclude current table
        });

        if (existing) {
          const error = new Error(
            "Table number already exists for this restaurant",
          );
          error.statusCode = 409;
          throw error;
        }
      }

      // Prepare update fields (only allow certain fields)
      const updateFields = {};
      if (updateData.tableNumber !== undefined) {
        updateFields.tableNumber = updateData.tableNumber.trim();
      }
      if (updateData.capacity !== undefined) {
        updateFields.capacity = updateData.capacity;
      }
      if (updateData.status !== undefined) {
        updateFields.status = updateData.status;
      }
      if (updateData.isActive !== undefined) {
        updateFields.isActive = Boolean(updateData.isActive);
      }

      // Perform update
      const updated = await Table.findByIdAndUpdate(tableId, updateFields, {
        new: true,
      });

      return updated.toObject();
    } catch (error) {
      // Handle duplicate key error
      if (error.code === 11000) {
        const err = new Error(
          "Table number already exists for this restaurant",
        );
        err.statusCode = 409;
        throw err;
      }

      if (!error.statusCode) {
        error.statusCode = 500;
      }
      throw error;
    }
  }

  /**
   * Update table status
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {string} tableId - Table ID
   * @param {string} status - New status (available, occupied, reserved)
   * @returns {object} Updated table
   */
  async updateTableStatus(restaurantId, tableId, status) {
    try {
      // Find table first for ownership verification
      const table = await Table.findById(tableId);

      if (!table) {
        const error = new Error("Table not found");
        error.statusCode = 404;
        throw error;
      }

      // CRITICAL SECURITY: Verify ownership
      if (table.restaurantId.toString() !== restaurantId) {
        const error = new Error(
          "Forbidden: Table does not belong to your restaurant",
        );
        error.statusCode = 403;
        throw error;
      }

      // Validate status enum
      const validStatuses = ["available", "occupied", "reserved"];
      if (!validStatuses.includes(status)) {
        const error = new Error(
          `Invalid status. Must be one of: ${validStatuses.join(", ")}`,
        );
        error.statusCode = 400;
        throw error;
      }

      // Update status
      const updated = await Table.findByIdAndUpdate(
        tableId,
        { status },
        { new: true },
      );

      return updated.toObject();
    } catch (error) {
      if (!error.statusCode) {
        error.statusCode = 500;
      }
      throw error;
    }
  }

  /**
   * Delete table (soft delete - set isActive to false)
   * @param {string} restaurantId - Restaurant ID from JWT context
   * @param {string} tableId - Table ID to delete
   * @returns {object} Deleted table
   */
  async deleteTable(restaurantId, tableId) {
    try {
      // Find table
      const table = await Table.findById(tableId);

      if (!table) {
        const error = new Error("Table not found");
        error.statusCode = 404;
        throw error;
      }

      // CRITICAL SECURITY: Verify table belongs to current restaurant
      if (table.restaurantId.toString() !== restaurantId) {
        const error = new Error(
          "Forbidden: Cannot delete another restaurant's table",
        );
        error.statusCode = 403;
        throw error;
      }

      // Soft delete: set isActive to false instead of hard delete
      const deleted = await Table.findByIdAndUpdate(
        tableId,
        { isActive: false },
        { new: true },
      );

      return deleted.toObject();
    } catch (error) {
      if (!error.statusCode) {
        error.statusCode = 500;
      }
      throw error;
    }
  }
}

module.exports = new TableService();
